[Add] troubleshooting guide / keep getting the not connected to wi-fi or vpn error
SideStore/SideStore-Docs pull request #56
Opened 2024-12-29 19:41 UTC by neoarz

2024-12-30 04:09 UTC, polymo1 requested changes

2024-12-30 04:09 UTC, polymo1 commented on docs/troubleshooting/troubleshooting.mdx
> +2. Make sure Wi-Fi is not restricted (such as school Wi-Fi).
maybe something closer to:

"Ensure that Apple domains, and the domain for your anisette server, are not restricted (e.g. school/work Wi-Fi)"

2024-12-30 04:09 UTC, polymo1 commented on docs/troubleshooting/troubleshooting.mdx
> +4. Turn off, turn on WireGuard, and wait a few seconds in SideStore before trying to refresh.
```
- Turn off, turn on
+ Turn off, then turn back on
```

2024-12-30 04:09 UTC, polymo1 commented on docs/troubleshooting/troubleshooting.mdx
> +   - After creating a new pairing file, go to sidestore settings and press "Reset pairing file", then choose the new pairing file you just created.
```
- sidestore
+ SideStore
```

2024-12-30 04:33 UTC, neoarz commented on docs/troubleshooting/troubleshooting.mdx
> +   - After creating a new pairing file, go to sidestore settings and press "Reset pairing file", then choose the new pairing file you just created.
fixed

2024-12-31 04:01 UTC, polymo1 commented
lgtm

2024-12-31 04:01 UTC, merged